# Generated by Django 5.0.6 on 2024-05-16 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInClassroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.classroom')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.student')),
            ],
        ),
    ]
