# Generated by Django 5.0.6 on 2024-05-16 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_studentinclassroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentInClassroom',
        ),
    ]
